//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckInPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class STD_Table
    {
        public int STD_ID { get; set; }
        public string STD_NAME { get; set; }
        public string STD_ENTRANCE { get; set; }
        public string STD_RESIDENCE { get; set; }
    }
}
